apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - deployment.yaml
  - service.yaml
  - kubernetes-api-service.yaml
  - rbac.yaml
  - httproute.yaml
  - backend-tls-policy.yaml
  - backendtrafficpolicy.yaml
