apiVersion: v1
kind: ServiceAccount
metadata:
  name: activity-apiserver
  namespace: activity-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: activity-processor
  namespace: activity-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: activity-controller-manager
  namespace: activity-system
