apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-event-exporter
  namespace: activity-system
  labels:
    app: k8s-event-exporter
    app.kubernetes.io/name: k8s-event-exporter
    app.kubernetes.io/component: event-forwarder
