apiVersion: v1
kind: Service
metadata:
  name: k8s-event-exporter
  namespace: activity-system
  labels:
    app: k8s-event-exporter
    app.kubernetes.io/name: k8s-event-exporter
    app.kubernetes.io/component: event-forwarder
spec:
  ports:
  - name: health
    port: 8081
    protocol: TCP
    targetPort: health
  selector:
    app: k8s-event-exporter
  type: ClusterIP
