apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: activity-system
spec:
  type: oci
  interval: 1h
  url: oci://registry-1.docker.io/bitnamicharts
  timeout: 3m
