apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - statefulset.yaml
  - service.yaml

# Component metadata
metadata:
  name: etcd
  annotations:
    config.kubernetes.io/local-config: "true"
