apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - keeper-installation.yaml
  - pod-disruption-budget.yaml

# Component metadata
metadata:
  name: clickhouse-keeper
  annotations:
    config.kubernetes.io/local-config: "true"
