apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - clickhouse-installation.yaml

# Component metadata
metadata:
  name: clickhouse-standalone
  annotations:
    config.kubernetes.io/local-config: "true"
