apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: rustfs
  namespace: rustfs-system
spec:
  type: oci
  interval: 1h
  url: oci://registry-1.docker.io/cloudpirates
  timeout: 3m
