apiVersion: iam.miloapis.com/v1alpha1
kind: Role
metadata:
  name: activity.miloapis.com-audit-log-querier
  namespace: milo-system
  labels:
    app.kubernetes.io/name: audit-log-querier
    app.kubernetes.io/part-of: activity.miloapis.com
spec:
  launchStage: Beta
  includedPermissions:
    - activity.miloapis.com/auditlogqueries.create
    - activity.miloapis.com/auditlogfacetsqueries.create
