apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - keeper-installation.yaml

# Component metadata
metadata:
  name: clickhouse-keeper-standalone
  annotations:
    config.kubernetes.io/local-config: "true"
