apiVersion: iam.miloapis.com/v1alpha1
kind: ProtectedResource
metadata:
  name: activity.miloapis.com-eventqueries
spec:
  serviceRef:
    name: "activity.miloapis.com"
  kind: EventQuery
  plural: eventqueries
  singular: eventquery
  permissions:
    - create
  parentResources:
    - apiGroup: resourcemanager.miloapis.com
      kind: Organization
    - apiGroup: resourcemanager.miloapis.com
      kind: Project
    - apiGroup: iam.miloapis.com
      kind: User
