apiVersion: iam.miloapis.com/v1alpha1
kind: ProtectedResource
metadata:
  name: activity.miloapis.com-events
spec:
  serviceRef:
    # The activity service exposes events through the k8s events API for
    # compatibility.
    name: "events.k8s.io"
  kind: Event
  plural: events
  singular: event
  permissions:
    - list
    - watch
  parentResources:
    - apiGroup: resourcemanager.miloapis.com
      kind: Organization
    - apiGroup: resourcemanager.miloapis.com
      kind: Project
    - apiGroup: iam.miloapis.com
      kind: User
