apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - activities.yaml
  - activityqueries.yaml
  - activityfacetqueries.yaml
  - auditlogqueries.yaml
  - auditlogfacetsqueries.yaml
  - policypreviews.yaml
  - events.yaml
  - eventqueries.yaml
  - eventfacetqueries.yaml
