apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: activity-reindex-worker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: activity-reindex-worker
subjects:
- kind: ServiceAccount
  name: activity-reindex-worker
  namespace: activity-system
