name: Publish UI to NPM

on:
  push:
    branches:
      - main
    paths:
      - "ui/**"
      - "!ui/example/**"

jobs:
  publish:
    uses: datum-cloud/actions/.github/workflows/publish-npm-package.yaml@v1.9.0
    with:
      package-name: "@miloapis/activity-ui"
      package-path: ui
    secrets: inherit
